import Link from "next/link";
import Header from "../components/Header";
import Footer from "../components/Footer";

export default function TermsOfUsePage() {
  return (
    <main className="min-h-screen bg-white pt-20">
      <Header />

      {/* Header Banner */}
      <section className="bg-[#005f91] py-16 text-white px-5 sm:px-8 lg:px-10">
        <div className="mx-auto w-full max-w-7xl">
          <h1 className="text-[32px] font-bold leading-tight sm:text-[40px]">
            Terms of Use
          </h1>
        </div>
      </section>

      {/* Content Section */}
      <section className="px-5 py-12 sm:px-8 lg:px-10">
        <div className="mx-auto w-full max-w-4xl text-[#333]">
          <div className="prose prose-slate max-w-none text-[15px] leading-[1.75]">

            {/* Introduction */}
            <div className="mb-8 rounded-lg border border-slate-200 bg-slate-50/50 p-6 sm:p-8">
              <h2 className="text-[22px] font-bold text-[#0a1f44] mb-4">
                Welcome to Vidi Meth Digital Services OPC Private Limited !
              </h2>
              <p className="mb-4 text-[14px] text-slate-600">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
              </p>
              <p className="mb-4 text-[14px] text-slate-600">
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of{" "}
                <a href="https://www.vidimeth.com" className="text-[#005f91] underline font-medium hover:text-[#004a70]">
                  www.vidimeth.com
                </a>{" "}
                website.
              </p>
              <p className="mb-4 text-[14px] text-slate-600">
                The domain name <strong className="text-slate-800">www.vidimeth.com</strong> (hereinafter referred to as “Website”) is owned and operated by <strong className="text-slate-800">Vidi Meth Digital Services (OPC) Private Limited</strong> a company incorporated under the Companies Act, 1956 with its registered office at <span className="font-medium text-slate-700">147 Aambagan Road, Sakchi, Jamshedpur – 831001, Jharkhand, India</span> (hereinafter referred to as ”Vidi Meth Digital Services”).
              </p>
              <p className="text-[14px] text-slate-600 font-mono">
                Corporate Identity Number (CIN): <span className="font-bold text-[#005f91]">U52100JH2017OPC009718</span>
              </p>
            </div>

            <p className="mb-4">
              Your use of the Vidi Meth Digital Services and services and tools are governed by the following terms and conditions (hereinafter “Terms of Use”) as applicable to the Vidi Meth Digital Services including the applicable policies which are incorporated herein by way of reference.
            </p>

            <p className="mb-4">
              For the purpose of these Terms of Use, wherever the context so requires “You” or “User” shall mean any natural or legal person who has agreed to the User to surf the Website. The term “We”, “Us”, “Our” shall mean Vidi Meth Digital Services (OPC) Private Limited.
            </p>

            <p className="mb-4">
              By mere accessing or using of the Website, users signify they have carefully read, understood, agree, without limitation or qualifications to be bound by these Terms of Use. When user transact or avail any of the services provided by Us through the Website or browse through the website, (e.g. Product Reviews, associates parties), in present or future, users accept and agree to be bound of these Terms of Use, rules, guidelines, policies, terms, and conditions of Vidi Meth Digital Services’s service.
            </p>

            <p className="mb-6">
              We reserve the right, to changed, edited, altered, amended, modified, add or remove portions of these Terms of Use, at any time without any prior written notice to you. You shall ensure to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the modification will mean that You accept and agree to the revisions. As long as you comply with these Terms of Use (rules, guidelines, policies, terms, and conditions), we grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
            </p>

            {/* Important Notice Box */}
            <div className="my-8 rounded-md bg-[#fff8f0] p-5 border-l-4 border-[#ff6b00] text-[14.5px]">
              <p className="font-bold uppercase tracking-wide text-[#b34b00] mb-2">
                ATTENTION: PLEASE READ CAREFULLY BEFORE PROCEEDING
              </p>
              <p className="text-slate-800 leading-relaxed">
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. If you do not agree with these Terms of Use, Please do not use the website. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Vidi Meth Digital Services Policies, inter alia Privacy Policy (available at{" "}
                <Link href="/privacy-policy" className="font-semibold text-[#005f91] underline hover:text-[#004a70]">
                  Privacy Policy
                </Link>
                ) of the Company, which would be amended from time to time.
              </p>
            </div>

            {/* Eligibility */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-10 mb-3">Eligibility</h3>
            <p className="mb-4">
              The user should have completed 18 years of age and be competent to enter into a contract under Indian contract law. The Services are not available to minors under the age of eighteen (18) or to any Users suspended or removed from the Vidi Meth Digital Services system by Vidi Meth Digital Services for any reason whatsoever. If you are a minor i.e. under 18 years of age who is intending to avail the services of the Website should do so through his or her legal guardian in accordance with applicable law.
            </p>
            <p className="mb-8">
              VidiMeth Digital Services reserves the right to terminate your membership and / or refuse access to use the Services offered at the Website to new Users or to terminate access granted to existing Users at any time without according any reasons for doing so. You shall not have more than one active Account (defined hereunder) on the Website. Additionally, You are prohibited from selling, trading, or otherwise transferring Your Account to another person.
            </p>

            {/* Registration */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Registration</h3>
            <p className="mb-3">On registration You agree to:</p>
            <ul className="list-disc pl-6 mb-8 space-y-2">
              <li>
                Make Your contact details available to partners/business associates of the Platform. You may be contacted by the Platform or its partners for additional information and the registration process through email, Telephone, and SMS.
              </li>
              <li>
                Receive promotional mails/special offers from Platform or any of its partner websites/applications. If You do not wish to be contacted by Platform, please modify the settings at the time of registration or in the “Accounts & Settings” section on the Platform.
              </li>
            </ul>

            {/* User Account, Password and Security */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">User Account, Password and Security</h3>
            <p className="mb-4">
              You may access and use the Website, You shall be responsible for maintaining the confidentiality and security of the Account Information, and are fully responsible for all activities that occur under Your log-in ID (Display Name) and Password. You agree to:
            </p>
            <ul className="list-disc pl-6 mb-4 space-y-2">
              <li>Immediately notify Vidi Meth Digital Services of any unauthorized use of Your Account Information or any other breach of security, and</li>
              <li>Ensure that You exit from Your Account at the end of each session.</li>
            </ul>
            <p className="mb-4">
              VidiMeth Digital Services cannot and will not be liable for any loss or damage arising from Your failure to comply with this section. You may be held liable for losses incurred by Vidi Meth Digital Services or any other user of or visitor to the Website due to authorized or unauthorized use of Your Account as a result of Your failure in keeping Your Account Information secure and confidential. You shall ensure that the Account Information provided by You in the Website’s registration form is complete, accurate and up-to-date. Use of another user’s Account Information for availing the Services is expressly prohibited.
            </p>
            <p className="mb-8">
              If You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.
            </p>

            {/* Communications */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Communications</h3>
            <p className="mb-8">
              When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.
            </p>

            {/* Platform for Transaction and Communication */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Platform for Transaction and Communication</h3>
            <p className="mb-4">
              Platform for Communication the Website is only a venue where Users may meet and interact with one another for their transactions. Vidi Meth Digital Services is not and cannot be a party to or control in any manner any transaction between two Users of the Website.
            </p>
            <p className="mb-3 font-medium text-[#0a1f44]">Consequently:</p>
            <ol className="space-y-3.5 mb-8 text-slate-800">
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                <span>All commercial/contractual terms are offered by and agreed to between users of the website alone.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                <span>VidiMeth Digital Services does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the services proposed to be sold or offered to be sold or purchased on the Website.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                <span>VidiMeth Digital Services does not implicitly or explicitly support or endorse the sale or purchase of any services on the Website. Vidi Meth Digital Services accepts no liability for any errors or omissions, whether on behalf of itself or third parties.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                <span>VidiMeth Digital Services platform shall not be utilized to upload, post, email, transmit or otherwise make available either directly or indirectly, any unsolicited bulk e-mail or unsolicited commercial e-mail by the user. Vidi Meth Digital Services reserves the right to filter and monitor and block the emails sent by users using the servers maintained by Vidi Meth Digital Services to relay emails. All attempts shall be made by Vidi Meth Digital Services and the user to abide by International Best Practices in containing and eliminating Spam.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                <span>Users shall not spam the database maintained by Vidi Meth Digital Services or indiscriminately and repeatedly forward mail that may be considered spam etc. Any conduct of the user in violation of this clause shall entitle Vidi Meth Digital Services to forthwith terminate all services to the user without notice and to forfeit any amounts paid by him.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vi)</span>
                <span>The user shall not upload, post, transmit, publish, or distribute any material or information that is unlawful, or which may potentially be perceived as being harmful, threatening, abusive, harassing, defamatory, libellous, vulgar, obscene, or racially, ethnically, or otherwise objectionable.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vii)</span>
                <span>The User is solely responsible for maintaining confidentiality of the User password and user identification and all activities and transmission performed by the User through his user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and Vidi Meth Digital Services assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(viii)</span>
                <span>The User/Subscriber/Visitor to Vidi Meth Digital Services and/or its affiliated websites does hereby specifically agree that he/she shall, at all times, comply with the requirements of the Information Technology Act, 2000 as also rules, regulations, guidelines, bye laws and notifications made there under, while assessing or feeding any resume/ insertion or information/data into the computers, computer systems or computer network of Vidi Meth Digital Services. The said User/ subscriber/ visitor to Vidi Meth Digital Services and/or its affiliated websites does further unequivocally declare that in case he violates any provisions of the Information Technology Act, 2000 and/or rules, regulations, guidelines, byelaws and notifications made there under, he shall alone be responsible for all his acts, deeds and things and that he alone shall be liable for civil and criminal liability there under or under any other law for the time being in force.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ix)</span>
                <span>The user shall not infringe on any intellectual property rights of any person / entity or retain information / download any information from any computer system or otherwise with an intention to do so.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(x)</span>
                <span>Vidi Meth Digital Services will make best efforts to do so but does not warrant that any of the websites or any affiliate site(s) or network system linked to it is free of any operational errors nor does it warrant that it will be free of any virus, computer contaminant, worm, or other harmful components. The subscription of a user shall be subject to Quotas as applicable and as advised. e-mails provided as part of contact details are expected to be genuine and access to such email accounts is available to authorized personnel only.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xi)</span>
                <span>Vidi Meth Digital Services shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user’s account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xii)</span>
                <span>Payments for the services offered by Vidi Meth Digital Services shall be on a 100% advance basis. Refund if any will be at the sole discretion of Vidi Meth Digital Services offers no guarantees whatsoever for the accuracy or timeliness of the refunds reaching the Customers card/bank accounts. Vidi Meth Digital Services gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only. Vidi Meth Digital Services undertakes no liability for free services.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiii)</span>
                <span>In case a person using the world wide web/internet receives a spam or virus which includes a link to Vidi Meth Digital Services or to any other site maintained, operated or owned by Vidi Meth Digital Services (OPC) Private Limited, it should not be held responsible for the same. Vidi Meth Digital Services assumes no responsibility for such mails.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiv)</span>
                <span>Vidi Meth Digital Services neither guarantees nor offers any warranty about the credentials bonafides, status or otherwise of the prospective employer/organization which downloads the resume/ insertion or information/data and uses it to contact the user. Vidi Meth Digital Services would not be held liable for loss of any data technical or otherwise, or of the resume/ insertion or information/data or particulars supplied by user due to acts of god as well as reasons beyond its control like corruption of data or delay or failure to perform as a result of any cause(s) or conditions that are beyond Vidi Meth Digital Services’s reasonable control including but not limited to strikes, riots, civil unrest, govt. policies, tampering of data by unauthorized persons like hackers, distributed denial of service attacks, virus attacks, war and natural calamities.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xv)</span>
                <span>Vidi Meth Digital Services undertakes to take all reasonable precautions at its end to ensure that there is no leakage/misuse of the password granted to the subscriber. It shall be the sole responsibility of the user to ensure that it uses the privacy setting options as it deems fit to debar / refuse access of the data fed by it, to such corporate entities individuals, or consultants.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xvi)</span>
                <span>User further represents that the products/services purchased are not for resale to others.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xvii)</span>
                <span>Vidi Meth Digital Services shall not and is not required to mediate or resolve any dispute or disagreement between employee and employers.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xviii)</span>
                <span>You release and indemnify Vidi Meth Digital Services and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Vidi Meth Digital Services cannot take responsibility or control the information provided by other Users which is made available on the website. You may find other User’s information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xix)</span>
                <span>Please note that there could be risks in dealing with underage persons or people acting under false pretence.</span>
              </li>
            </ol>

            {/* User Conduct and Rules on the Website */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-10 mb-3">User Conduct and Rules on the Website</h3>
            <p className="mb-4">
              The user agrees and undertakes that the reviews, comments and other information provided or posted or uploaded on the website are not false, incomplete, distorted, manipulated, fraudulent or misleading. The user agrees, undertakes and confirms that when using or accessing the website shall be strictly governed by the following binding principle:
            </p>
            <p className="mb-3 font-medium text-[#0a1f44]">
              1. User will not host, display, upload, modify, publish, transmit, update or share any information (objectionable contents) that:
            </p>
            <ol className="space-y-3 mb-6 text-slate-800">
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                <span>Does not belong to you and to which you have no right</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                <span>Grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                <span>Harms minors in any way</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                <span>Misleading in any way</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                <span>Impersonates any person or entity, or falsely states or otherwise misrepresents your affiliation with a person or entity</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vi)</span>
                <span>Patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vii)</span>
                <span>Harasses or advocates harassment of another person</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(viii)</span>
                <span>Involves the transmission of “junk mail”, “chain letters”, or unsolicited mass mailing or “spamming”</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ix)</span>
                <span>Promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(x)</span>
                <span>Infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen items</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xi)</span>
                <span>Contains software viruses or any other computer code, files or programs designed to interrupt destroy or limit the functionality of any computer resource; or contains any Trojan horses, worms, time bombs, cancel bots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xii)</span>
                <span>Disrupts or interferes with the security of, or otherwise causes harm to, the website, systems resources, accounts, passwords, servers or networks connected to or accessible through the websites or any affiliated or linked sites.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiii)</span>
                <span>Uses the Website or Content for any purpose that is unlawful or prohibited by the Agreement, or to solicit the performance of any illegal activity or other activity which infringes the rights of Vidi Meth Digital Services or other third parties;</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiv)</span>
                <span>Tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xv)</span>
                <span>Solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xvi)</span>
                <span>Violates any law for the time being in force;</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xvii)</span>
                <span>Deceives or misleads the addressee/users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xviii)</span>
                <span>Impersonates another person.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xix)</span>
                <span>Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xx)</span>
                <span>Falsifies or deletes any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is uploaded.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xxi)</span>
                <span>Violates any code of conduct or other guidelines, which may be applicable for or to any particular Service;</span>
              </li>
            </ol>

            <div className="space-y-4 mb-8 text-slate-800">
              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">2.</strong>
                The user shall not use any deep-link, page-scrape, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the website.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">3.</strong>
                You shall not attempt to gain unauthorized access to any portion or feature of the website, or any other systems or networks connected to the website or to any server, computer, network, or to any of the services offered on or through the website, by hacking, password “mining” or any other illegitimate means.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">4.</strong>
                The user undertakes not to attempt to circumvent or modify any security technology or software that is part of the website. The user also agrees not to use any device, software or routine to interfere, engage or assist any other person, to circumvent or modify any security technology or software that is part of the website. The user should also not obscure or obstruct any features of the website. The user undertakes not to copy, modify, create a derivative work of, reverse engineer, decompile or otherwise attempt to extract the source code of the website or any part thereof without a specific written permission from Vidi Meth Digital Services to do so.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">5.</strong>
                You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">6.</strong>
                You may need to install updates that we or any third party introduce from time to time to use the services, Products, Website including downloads and required functionality, such as bug fixes, patches, enhanced functions, missing plug-ins and new versions (collectively, “Updates”). Your use of the Products or Website you have installed requires that you have agreed to receive such automatically requested Updates.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">7.</strong>
                You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Vidi Meth Digital Services and / or others.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">8.</strong>
                You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Website or related to us.
              </p>

              <p className="leading-relaxed">
                <strong className="text-[#005f91] mr-1.5">9.</strong>
                It is possible that other users (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We does not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website.
              </p>
            </div>

            {/* Indemnification Box */}
            <div className="my-8 bg-[#0a1f44] text-white p-6 rounded-md shadow-sm">
              <p className="text-[14px] leading-relaxed">
                BY ACCEPTING THESE TERMS OF USE, YOU AGREE TO INDEMNIFY AND OTHERWISE HOLD HARMLESS VIDI METH DIGITAL SERVICES, ITS DIRECTORS, OFFICERS, EMPLOYERS, AGENTS, SUBSIDIARIES, AFFILIATES AND OTHER PARTNERS FROM ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES ARISING OUT OF, RELATING TO, OR RESULTING FROM YOUR USE OF THE SERVICES OBTAINED THROUGH VIDIMETH.COM INCLUDING BUT NOT LIMITED TO INFORMATION PROVIDED BY YOU OR ANY OTHER MATTER RELATING TO VIDIMETH.COM. ANY REFERENCE TO DUTIES AND TAXES ETC IN THESE TERMS OF USE SHALL INCLUDE GOODS AND SERVICES TAX (HEREIN REFERRED AS GST) FROM THE DATE GST LAW IS IMPLEMENTED IN INDIA. ANY ADDITIONAL TAX LIABILITY ARISING ON ACCOUNT OF INTRODUCTION OF GST (WHETHER ON ACCOUNT OF INCREASE IN RATE OR ANY CHANGE BROUGHT IN BY THE NEW TAX REGIME) WOULD BE RECOVERED OVER AND ABOVE THE AGREED CONTRACT PRICE / SERVICE FEE.
              </p>
            </div>

            {/* Disclaimer for websites that we link to */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">
              Disclaimer for websites that we link to
            </h3>
            <p className="mb-3 font-medium text-[#0a1f44]">We use our best endeavours to ensure that:</p>
            <ol className="list-decimal pl-6 mb-4 space-y-2 text-slate-800 font-medium">
              <li>the websites/apps we select for inclusion in the Platform work, and continue to work properly;</li>
              <li>their content remains acceptable and useful; and</li>
              <li>their operation will not be injurious to our users’ devices.</li>
            </ol>
            <p className="mb-3 font-medium text-[#0a1f44]">
              We explicitly disclaim, and will not accept any responsibility for any of the following in respect of the sites that we link to:
            </p>
            <ol className="list-decimal pl-6 mb-8 space-y-2 text-slate-800 font-medium">
              <li>Infection by computer viruses</li>
              <li>Damage caused by downloaded software</li>
              <li>Technical problems, failures and speed of operation</li>
              <li>Libelous or illegal material</li>
              <li>The quality or truth of any material, or advice that is offered</li>
            </ol>

            {/* Privacy */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Privacy</h3>
            <p className="mb-8">
              We view protection of your privacy policy as a very important principle. We understand clearly that You and Your Personal Information is one of our most important assets. We request to you please read this Privacy Policy carefully, by accessing or using our website. VidiMeth Digital Services respects your privacy and is committed to protecting it. For more details, please see our{" "}
              <Link href="/privacy-policy" className="text-[#005f91] underline font-medium hover:text-[#004a70]">
                Privacy Policy
              </Link>
              . If You object to Your Information being transferred or used in this way please do not use Website.
            </p>

            {/* Terms of conditions specific for educational institutions */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">
              Terms &amp; conditions specific for educational institutions / colleges etc. (as applicable)
            </h3>
            <ol className="list-decimal pl-6 mb-4 space-y-3 text-slate-800 font-medium">
              <li>You will comply with all applicable data protection laws in relation to the processing of personal data; and not process personal data in an unlawful manner and excessive with regard to agreed purposes as defined in the privacy policy and this terms and conditions</li>
              <li>You shall implement adequate technical and organizational controls to protect the shared personal data obtained from the Company against unauthorised or unlawful processing and against accidental loss, destruction, damage, alteration or disclosure</li>
              <li>You agree to provide reasonable assistance as is necessary to facilitate the handling of any Data Security Breach (as applicable under GDPR or any other privacy law as applicable) in an expeditious and compliant manner</li>
              <li>You agree that the responsibility for complying with a data subject request lies with the Party which holds/processes the Personal Data collected/shared</li>
              <li>You warrant and represent that the institution shall not disclose or transfer Personal Data obtained from the Company to any sub-processors without ensuring that adequate and equivalent safeguards to the Personal Data.</li>
              <li>You shall retain or process shared Personal Data for no longer than is necessary to carry out the agreed purposes.</li>
            </ol>
            <p className="mb-4 text-slate-700">
              Platform and the educational institutions etc. (as applicable) would act as independent controllers in their respective capacity. For more details please visit the data protection amendment:
            </p>
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Payments Related Information</h3>
            <div className="my-4 p-4 bg-slate-100 border-l-4 border-[#005f91] font-bold text-[#0a1f44]">
              YOU ARE REQUESTED TO HONOUR YOUR PAYMENT OBLIGATIONS TO THE COMPANY.
            </div>
            <ol className="space-y-3.5 mb-8 text-slate-800">
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                <span>Payments for the services offered by the Platform shall be on a 100% advance basis. The payment for service once subscribed to by you is not refundable and any amount paid shall stand appropriated. Refund, if any, will be at the sole discretion of the Company.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                <span>User hereby irrevocably accepts to receive the tax invoice as soft copy through emails.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                <span>Notwithstanding anything contained in any other agreement or arrangement, by whatever name called, the performance obligation of the Company (service provider) is to provide access of its on-line portal to the customer for the duration of the subscription period &amp; reference to any usage, by whatever name called or any other performance obligation, if any, is to provide the upper limit for consumption, which by itself, does not create any additional performance obligation upon the Company.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                <span>In the event of any suspension or termination of services on account of non-compliance of these Terms of Use, any payment made to the Company by you shall stand forfeited with immediate effect.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                <div>
                  <span>While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</span>
                  <ul className="list-circle pl-6 mt-2 space-y-1.5 text-slate-700">
                    <li>Lack of authorization for any transaction/s, or</li>
                    <li>Any payment issues arising out of the transaction, or</li>
                    <li>Exceeding the preset limit mutually agreed by You and between “Bank/s”, or</li>
                    <li>Decline of transaction for any other reason/s</li>
                  </ul>
                </div>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vi)</span>
                <span>All payments made against the purchases/services on Website by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Website will not facilitate transaction with respect to any other form of currency with respect to the purchases made on Website.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(vii)</span>
                <span>The User acknowledges and agrees that Company/Platform, at its sole discretion and without prejudice to other rights and remedies that it may have under the applicable laws, shall be entitled to set off the amount excess paid by a subscriber/user against any amount(s) payable by User to Company under any other agreement or commercial relationship towards other products/services. The Company gives no guarantees of server uptime or applications working properly. All is on a best effort basis and liability is limited to refund of amount only.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(viii)</span>
                <span>You understand, accept and agree that the payment facility provided by Vidi Meth Digital Services is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment through collection and remittance facility for the Transactions on the Vidi Meth Digital Services Website using the existing authorized banking infrastructure and Credit Card payment gateway networks.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(ix)</span>
                <span>Vidi Meth Digital Services reserves the right to refuse to process Transactions by users with a prior history of questionable charges including without limitation breach of any agreements by user with Vidi Meth Digital Services website or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(x)</span>
                <span>Users, buying the products online are redirected to third party gateways for completing payment transactions. These transactions happen on third party network and hence not controlled by Company.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xi)</span>
                <span>A User through his user identification and shall be solely responsible for carrying out any online or off-line transaction involving credit cards / debit cards or such other forms of instruments or documents for making such transactions and Company assumes no responsibility or liability for their improper use of information relating to such usage of credit cards / debit cards used by the subscriber online / off-line.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xii)</span>
                <span>The Company shall not be liable for any loss or damage sustained by reason of any disclosure (inadvertent or otherwise) of any information concerning the user’s account and / or information relating to or regarding online transactions using credit cards / debit cards and / or their verification process and particulars nor for any error, omission or inaccuracy with respect to any information so disclosed and used whether or not in pursuance of a legal process or otherwise.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiii)</span>
                <span>The User or customer shall be required to promptly provide copy of TDS certificate to the Company as mandated under law for tax deducted at source from the payments made to the Company. Any loss on account of non-availment or disallowance of such TDS credit in view of any lapse as per this clause or as required under applicable law on the part of User or customer shall entitle the company to seek reimbursement or indemnification.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xiv)</span>
                <span>User shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and Vidi Meth Digital Services Website.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xv)</span>
                <span>All Valid Credit/Debit/Cash Card/and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.</span>
              </li>
              <li className="flex items-start gap-2.5">
                <span className="font-semibold text-[#005f91] shrink-0">(xvi)</span>
                <span>All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.</span>
              </li>
            </ol>

            {/* Intellectual Property Rights */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Intellectual Property Rights</h3>
            <p className="mb-4">
              All content included on the Website, such as text, graphics, logos, photographs, trademark, button icons, images, sound, music, artwork, audio clips, digital downloads, data compilations, and software, is the property of Vidi Meth Digital Services its affiliates, associates’ parties or service provider and is protected by India and international copyright, authors’ rights and database right laws. The compilation of all content on the Website is the exclusive property of Vidi Meth Digital Services, its affiliates, associates’ parties or service provider and is protected by laws of India and international copyright and database right laws.
            </p>
            <p className="mb-4">
              VidiMeth Digital Services grants the user a limited license to access and make personal use of this Website, but not to download (other than page caching) or modify it, or any portion of it, except with express written consent of Vidi Meth Digital Services. This license does not include any resale or commercial use of the contents of the Website; any collection and use of any product listings, descriptions, or prices; any derivative use of this Website or its contents; any downloading or copying of account information for the benefit of another parties.
            </p>
            <p className="mb-4">
              The trademarks, logos and service marks displayed on the Website (“Marks“) are the property of Vidi Meth Digital Services or its parent company and other associated parties and service provider. Users are not permitted to use the Marks without the prior consent of Vidi Meth Digital Services, the associates or affiliates or contents suppliers or users or the third party that may own the Marks.
            </p>
            <p className="mb-4">
              VidiMeth Digital Services owns all intellectual property rights to and into the trademark ”Vidi Meth Digital Services” and the Website, including, without limitation, any and all rights, title and interest in and to copyright, related rights, patents, utility models, designs, know-how, trade secrets and inventions, goodwill, source code, meta tags, databases, text, content, graphics, icons, and hyperlinks.
            </p>
            <p className="mb-4">
              The users agree that they shall not use or apply for registration of any marks, or domain names which are similar to the marks or domain names used in connection with the Website or owned by Vidi Meth Digital Services.
            </p>
            <p className="mb-4">
              You shall not copy, reproduce, modify, alter, change, amend, transmit, broadcast, edit, revise, review, adapt, translate, distribute, perform, display, sell or otherwise deal with content or the intellectual property rights of the Website or content suppliers or third parties in any mode medium or manner now known or developed in future without authorization from Vidi Meth Digital Services.
            </p>
            <p className="mb-8">
              Users are strictly prohibited from framing or use framing techniques to enclose any content or intellectual property on the Website to illegally and unlawfully exploit the content or intellectual property rights owned by Vidi Meth Digital Services or other associated parties or service provider or third party as the case is.
            </p>

            {/* Disclaimer of Warranties and Liability */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Disclaimer of Warranties and Liability</h3>
            <p className="mb-4">
              The User expressly agree that the use of the website is at the user’s sole risk. The Website, service, content, user account and any third party content are provided by Vidi Meth Digital Services on an “as is” and “as available” basis without any representation or warranty of any kind, express, implied, statutory or otherwise including the implied warranties of title, non-infringement, accuracy, suitability, reliability, timelines, completeness, safety, performance, merchantability or fitness for a particular purpose permitted by applicable Indian law. Without prejudice to the forgoing paragraph, Vidi Meth Digital Services does not warrant that:
            </p>
            <ol className="list-decimal pl-6 mb-4 space-y-2 text-slate-800 font-medium">
              <li>The website or the services will be uninterrupted, timely, secure or error-free,</li>
              <li>This Website will be constantly available or available at all;</li>
              <li>The information on this Website is complete, true, accurate or non-misleading</li>
              <li>Any errors or defects in the website or services will be corrected.</li>
            </ol>
            <p className="mb-4">
              No advice or information, whether oral or written, obtained by you from Vidi Meth Digital Services or through the website / content or from use of the services shall create any warranty not expressly stated in these Terms of Use.
            </p>
            <p className="mb-4">
              You expressly understand and agree that, to the maximum extent permitted by applicable law Vidi Meth Digital Services will not be liable to You in any way or in relation to the Contents of, or unauthorised use of your account or account information in connection with the Website or any services, either with or without your knowledge. Vidi Meth Digital Services does not warrant that this site; nor makes any representations regarding the quality, accuracy or completeness of any data, information, Contents, materials or services included on or otherwise made available to You through the Website; their servers; or electronic communication sent from Us are free of viruses or other harmful components.
            </p>
            <p className="mb-8">
              VidiMeth Digital Services shall not be responsible for the delay, or inability to use the website or related functionalities, the provision of or failure to provide functionalities, or for any information, software, products, functionalities and related graphics obtained through the website or otherwise arising out of the use of website, whether based on contract, tort, negligence, strict liability.
            </p>

            {/* Disclaimer of online availability, impressions, and click-through */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">
              Disclaimer of online availability, impressions, and click-through
            </h3>
            <p className="mb-8">
              In addition to the other disclaimers and limitations discussed in this notice, there are no guarantees and no warranties regarding online availability, impressions, and click-through of the Website, its web pages, the Application and any material, information, links, or content presented on the web pages that may be accessible through the Platform. Platform reserves the right although it is under no obligation to ensure that advertising sponsors and advertising must be approved by Company before the posting of any advertising material, information, links, content, banners, and graphics on the Platform, however, the same may be reported by contacting us. Any advertising should be related to interactive digital television and related subject areas. Company reserves the right to accept or to reject any advertising sponsor or any advertising for any reason.
            </p>

            {/* Purchasing and Ordering Disclaimer */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Purchasing and Ordering Disclaimer</h3>
            <p className="mb-3 font-semibold text-[#0a1f44]">Make Your Own Decisions:</p>
            <p className="mb-4">
              If You are making or planning to make any decision, whether personal or business decisions, based on the content on the site, You should conduct an independent verification before making Your important decision. In the case of any listings or banners displaying any content related to any educational products, You may contact the institution/individual directly. All decisions made would be entirely Your prerogative and Company does not claim to offer any advice, either legal or financial. Company doesn’t take any ownership, directly or indirectly towards any person whatsoever, with respect to banners hosted on its Platform by its customers, which are strictly in the nature of sale of space by Platform &amp; it has not carried out any independent verification on the authenticity or compliance requirements, as may have been required under any law for the time being in force, of such images/ banners/ listings.
            </p>
            <p className="mb-4">
              <strong className="text-[#0a1f44]">Read These Terms.</strong> In purchasing/subscribing to a product/service offered on this platform you are advised to read these terms carefully before proceeding further. You hereby understand and agree to the terms below. If you do not understand and agree with these terms then do not place an order for a product/service.
            </p>
            <p className="mb-4">
              <strong className="text-[#0a1f44]">Pricing.</strong> All prices are subject to change without notice. Every effort has been made to ensure accurate pricing of the products/services featured on our platform. In the event a part or accessory is ordered and the listed price has changed, you will be notified prior to our processing your order.
            </p>
            <p className="mb-4">
              <strong className="text-[#0a1f44]">Purchase “AS IS.”</strong> All products/services are provided by the company on “as is” basis with no representations or warranties of any kind from the company, including without limitation no warranties as to the nature and quantum of responses to any banner or listing displayed on the platform.
            </p>
            <p className="mb-8 font-medium text-[#0a1f44]">
              <strong className="text-[#0a1f44]">Your responsibility; damage limits:</strong> YOU HAVE SOLE RESPONSIBILITY FOR USE OF THE PRODUCTS/SERVICES YOU PURCHASE THROUGH THIS PLATFORM. IN NO EVENT SHALL VIDIMETH.COM BE LIABLE TO YOU IN RELATION TO THE PRODUCTS/SERVICES, OR YOUR USE, MISUSE OR INABILITY TO USE THE PRODUCTS, FOR ANY (1) INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, OR CONSEQUENTIAL DAMAGE (INCLUDING LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE); OR (2) DIRECT DAMAGES IN EXCESS OF THE AMOUNT YOU PAID THE COMPANY FOR THE APPLICABLE PRODUCT/SERVICE.
            </p>

            {/* Limitation of Liability */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Limitation of Liability</h3>
            <p className="mb-4">
              In no event shall Vidi Meth Digital Services its affiliates, associates’ parties or service providers be liable for any direct, indirect, incidental, special, incidental, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the website, its services or this agreement (however arising, including negligence).
            </p>
            <p className="mb-8">
              VidiMeth Digital Services’s liability in any circumstance is limited to the amount of fees, if any, paid by you to Vidi Meth Digital Services. Vidi Meth Digital Services its affiliates, associates’ parties or service providers and technology partners make no representations or Warranties about the accuracy, reliability, completeness, and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Website or that the operation of the website, will be error free and/or uninterrupted. Consequently, Vidi Meth Digital Services assumes no liability whatsoever for any monetary or other damage suffered by you on account of any interruption or errors in the operation of the Website.
            </p>

            {/* Taxes */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Taxes</h3>
            <p className="mb-8">
              ANY REFERENCE TO DUTIES AND TAXES ETC IN THESE TERMS OF USE SHALL INCLUDE GOODS AND SERVICES TAX (“GST”) OR VALUE ADDED TAX (VAT) AS PER LOCAL JURISDICTION OR ANY OTHER SIMILAR TAX OR DUTY, BY WHATEVER NAME CALLED (HEREIN REFERRED AS GST) AND SHALL BE CHARGED IN ADDITION TO THE BASIC AMOUNT, IN ACCORDANCE WITH RESPECTIVE LAWS &amp; REGULATIONS. YOU ARE REQUIRED TO PROVIDE TRUE &amp; CORRECT INFORMATION AS REQUIRED UNDER TAX LAWS, INCLUDING BUT NOT LIMITED TO SEZ UNIT OR USAGE THEREIN &amp; VIDI METH DIGITAL SERVICES OPC PRIVATE LIMITED (VMDSOPL) SHALL BE ENTITLED TO CONSIDER ANY INFORMATION AVAILABLE AS PER ITS RECORDS TO BE CORRECT &amp; TRUE &amp; DISCHARGE ITS TAX OBLIGATIONS ACCORDINGLY. IN CASE OF ANY DISCREPANCY OR CHANGE, THE USER IS REQUIRED TO PROMPTLY INTIMATE THE CORRECT OR UPDATED PARTICULARS TO THE COMPANY. THE COMPANY SHALL BE ENTITLED TO SEEK INDEMNIFICATION FROM USERS IF IT IS REQUIRED TO PAY ANY TAX, DUTY, FEE, INTEREST OR PENALTY IN VIEW OF INCORRECT OR INCOMPLETE INFORMATION OR DATA FURNISHED BY USER OR NOT GOT RECTIFIED/ UPDATED BY USER TIMELY.
            </p>

            {/* Indemnity */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Indemnity</h3>
            <p className="mb-3">
              Users agree to indemnify and hold harmless Vidi Meth Digital Services including affiliates, associates and their respective owners, licensee, directors, officers, agents, employees and partners from and against all actions, proceedings, claims, losses, damages and costs (including attorney fees) and other expenses suffered or incurred due to or attributable to or arising out of:
            </p>
            <ol className="list-decimal pl-6 mb-8 space-y-2 text-slate-800 font-medium">
              <li>violation of any applicable law, rules or regulations</li>
              <li>breach of any representations, warranties or covenants of the user</li>
              <li>breach of this Terms of Use, privacy Policy and other Policies;</li>
              <li>the rights (including infringement of intellectual property rights) of a third party.</li>
            </ol>

            {/* Links */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Links</h3>
            <p className="mb-8">
              The Site or third parties may provide links to other World Wide Web sites or resources. Because Vidi Meth Digital Services has no control over such sites and resources, you acknowledge and agree that Vidi Meth Digital Services is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that Vidi Meth Digital Services shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.
            </p>

            {/* Dispute Settlement */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Dispute Settlement</h3>
            <p className="mb-4">
              If any dispute arises between a user/users and Company arising out of use of the Platform or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of these Terms, the dispute shall be referred to a sole arbitrator who shall be an independent and neutral third party identified by the Company. Decision of the arbitrator shall be final and binding on both the parties to the dispute. The place of arbitration shall be Jamshedpur, Jharkhand, India. The Arbitration &amp; Conciliation Act, 1996 as amended, shall govern the arbitration proceedings.
            </p>
            <p className="mb-8">
              The Company will not be party to any legal proceedings between a User (e.g., a subscriber) and a party contacted through the site. In case Company is made a party in any legal proceedings, costs will be recovered from the party on whose behest the Company is involved in the matter, to which it otherwise has no control. Company however will abide with any court order served on it through due process.
            </p>

            {/* Local Laws */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Local Laws</h3>
            <p className="mb-8">
              Vidi Meth Digital Services controls and operates this website from its headquarters in Jamshedpur, India and makes no representation that the materials on the website are appropriate or available for use in other locations. If you use this website from other locations, you are responsible for compliance with applicable local laws including but not limited to the export and import regulations of other countries. Unless otherwise explicitly stated, all marketing or promotional materials found on this website are solely directed to individuals, companies or other entities located in India and comply with the laws prevailing for the time being in force in India. Disputes if any shall be subject to the exclusive jurisdiction of Courts at Jamshedpur, Jharkhand.
            </p>

            {/* Governing Law and Jurisdiction */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Governing Law and Jurisdiction</h3>
            <p className="mb-8">
              The Terms of Use of this agreement shall be governed by Indian law and the courts at Jamshedpur, Jharkhand shall only have exclusive jurisdiction to resolve any disputes.
            </p>

            {/* Trademark, Copyright and Restriction */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Trademark, Copyright and Restriction</h3>
            <p className="mb-8">
              This site is controlled and operated by Vidi Meth Digital Services and products are sold by (You) associates parties. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on website is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other website or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.
            </p>

            {/* Miscellaneous */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Miscellaneous</h3>
            <h4 className="text-[17px] font-semibold text-[#0a1f44] mt-4 mb-2">Amendment to these Terms:</h4>
            <div className="my-4 p-4 bg-slate-100 border-l-4 border-[#005f91] font-bold text-[#0a1f44] text-[14px]">
              COMPANY RESERVES ITS RIGHT TO AMEND / ALTER OR CHANGE ALL OR ANY DISCLAIMERS OR TERM(S) OR CONDITION(S) OF AGREEMENTS AT ANY TIME WITHOUT ANY PRIOR NOTICE.
            </div>
            <p className="mb-4">
              Businesses, environment and technology evolve and in order to accommodate the changing nature of the environment in which we operate as well to provide for any additional features that may be introduced in future, these Terms may need modifications or additions. Such modifications or additions shall be effective immediately upon posting of the modified Terms of Use on the Site.
            </p>
            <p className="mb-8 text-slate-600">
              You are advised to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions.
            </p>

            {/* Data Protection Amendment */}
            <div className="my-8 rounded-lg border border-slate-200 bg-slate-50/50 p-6">
              <h4 className="text-[18px] font-bold text-[#0a1f44] mb-2">Data Protection Amendment</h4>
              <p className="text-slate-600 mb-6 text-[14.5px]">
                In line with General Data Protection Regulation, the below mentioned obligations are drafted which will be applicable on both the parties
              </p>
              
              {/* Section 1: Definitions */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-1">1. Definitions</h5>
                <p className="text-slate-700 italic text-[14px] mb-3">For the purposes of the clauses:</p>
                <ol className="space-y-3 pl-2 text-slate-800">
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                    <span>“GDPR” means Regulation (EU) 2016/679 of the European Parliament and of the Council of 27th April 2016 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data and repealing Directive 95/46/EC.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                    <span>The “data exporter” shall mean the controller who transfers the personal data.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                    <span>The “data importer” shall mean the controller who agrees to receive from the data exporter personal data for further processing in accordance with the terms of these clauses and who is not subject to a third country’s system ensuring adequate protection.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                    <span>“Clauses” shall mean these contractual clauses, which are a free-standing document that does not incorporate commercial business terms established by the parties under separate commercial arrangements.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                    <span>“Data Protection Legislation” means the GDPR for as long as it is directly applicable in the European Union and any national implementing laws, regulations and secondary legislation, as amended or updated from time to time, in India, and then any successor legislation.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(vi)</span>
                    <span>“Data Subject” means a data subject as defined by the Data Protection Legislation.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(vii)</span>
                    <span>“Personal Data” means personal data as defined by the Data Protection Legislation.</span>
                  </li>
                </ol>
                <p className="mt-3 text-[13.5px] text-slate-600 bg-amber-50 border-l-4 border-amber-400 p-3 rounded-r-md">
                  <strong>Note:</strong> The terms “data exporter” and “data importers” are strictly for use within the context of this amendment which should be interpreted only as defined above, and do not carry the same meaning as defined under any other regulations.
                </p>
              </div>

              {/* Section 2: Obligations of the data exporter */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-1">2. Obligations of the data exporter</h5>
                <p className="text-slate-700 italic text-[14px] mb-3">The data exporter warrants and undertakes that:</p>
                <ol className="space-y-3 pl-2 text-slate-800">
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                    <span>The personal data have been collected, processed and transferred in accordance with the laws applicable to the data exporter.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                    <span>It has used reasonable efforts to determine that the data importer is able to satisfy its legal obligations under these clauses</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                    <span>It will provide the data importer, when so requested, with copies of relevant data protection laws or references to them (where relevant, and not including legal advice) of the country in which the data exporter is established.</span>
                  </li>
                </ol>
              </div>

              {/* Section 3: Obligations of the data importer */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-1">3. Obligations of the data importer</h5>
                <p className="text-slate-700 italic text-[14px] mb-3">The data importer warrants and undertakes that:</p>
                <ol className="space-y-3 pl-2 text-slate-800">
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                    <span>It will have in place appropriate technical and organisational measures to protect the personal data against accidental or unlawful destruction or accidental loss, alteration, unauthorised disclosure or access, and which provide a level of security appropriate to the risk represented by the processing and the nature of the data to be protected.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                    <span>It will have in place procedures so that any third party it authorises to have access to the personal data, including processors, will respect and maintain the confidentiality and security of the personal data. Any person acting under the authority of the data importer, including a data processor, shall be obligated to process the personal data only on instructions from the data importer. This provision does not apply to persons authorised or required by law or regulation to have access to the personal data.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                    <span>It has no reason to believe, at the time of entering into these clauses, in the existence of any local laws that would have a substantial adverse effect on the guarantees provided for under these clauses, and it will inform the data exporter (which will pass such notification on to the authority where required) if it becomes aware of any such laws.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                    <span>It will process the personal data for purposes described in the privacy policy and terms and conditions, and has the legal authority to give the warranties and fulfil the undertakings set out in these clauses.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                    <span>It will identify to the data exporter a contact point within its organisation authorised to respond to enquiries concerning processing of the personal data, and will cooperate in good faith with the data exporter, the data subject and the authority concerning all such enquiries within a reasonable time.</span>
                  </li>
                  <li className="flex items-start gap-2.5">
                    <span className="font-semibold text-[#005f91] shrink-0">(vi)</span>
                    <span>It will not disclose or transfer the personal data to a third party data controller without ensuring that adequate and equivalent safeguards to the Personal Data.</span>
                  </li>
                </ol>
              </div>

              {/* Section 4: Law applicable to the clauses */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-2">4. Law applicable to the clauses</h5>
                <p className="text-slate-800 leading-relaxed pl-2">
                  These clauses shall be governed by the law of the country in which the data exporter is established.
                </p>
              </div>

              {/* Section 5: Resolution of disputes with data subjects or the authority */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-2">5. Resolution of disputes with data subjects or the authority</h5>
                <div className="space-y-3 pl-2 text-slate-800 leading-relaxed">
                  <p>
                    In the event of a dispute or claim brought by a data subject or the authority concerning the processing of the personal data against either or both of the parties, the parties will inform each other about any such disputes or claims, and will cooperate with a view to settling them amicably in a timely fashion.
                  </p>
                  <p>
                    The parties agree to respond to any generally available non-binding mediation procedure initiated by a data subject or by the authority. If they do participate in the proceedings, the parties may elect to do so remotely (such as by telephone or other electronic means). The parties also agree to consider participating in any other arbitration, mediation or other dispute resolution proceedings developed for data protection disputes.
                  </p>
                  <p>
                    Each party shall abide by a decision of a competent court of the data exporter’s country of establishment or of the authority which is final and against which no further appeal is possible.
                  </p>
                </div>
              </div>

              {/* Section 6: Termination */}
              <div className="mb-6">
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-2">6. Termination</h5>
                <div className="space-y-4 pl-2 text-slate-800 leading-relaxed">
                  <p>
                    In the event that the data importer is in breach of its obligations under these clauses, then the data exporter may temporarily suspend the transfer of personal data to the data importer until the breach is repaired or the contract is terminated.
                  </p>
                  
                  {/* Paragraph a */}
                  <div className="flex items-start gap-2.5">
                    <span className="font-bold text-[#005f91] shrink-0">a.</span>
                    <div className="w-full">
                      <p className="font-medium mb-2 text-[#0a1f44]">In the event that:</p>
                      <ol className="space-y-2.5 pl-2 text-slate-800">
                        <li className="flex items-start gap-2.5">
                          <span className="font-semibold text-[#005f91] shrink-0">(i)</span>
                          <span>If the transfer of personal data to the data importer has been temporarily suspended by the data exporter for longer than one month pursuant to paragraph (a)</span>
                        </li>
                        <li className="flex items-start gap-2.5">
                          <span className="font-semibold text-[#005f91] shrink-0">(ii)</span>
                          <span>If compliance by the data importer with these clauses would put it in breach of its legal or regulatory obligations in the country of import</span>
                        </li>
                        <li className="flex items-start gap-2.5">
                          <span className="font-semibold text-[#005f91] shrink-0">(iii)</span>
                          <span>If the data importer is in substantial or persistent breach of any warranties or undertakings given by it under these clauses</span>
                        </li>
                        <li className="flex items-start gap-2.5">
                          <span className="font-semibold text-[#005f91] shrink-0">(iv)</span>
                          <span>If a final decision against which no further appeal is possible of a competent court of the data exporter’s country of establishment or of the authority rules that there has been a breach of the clauses by the data importer or the data exporter</span>
                        </li>
                        <li className="flex items-start gap-2.5">
                          <span className="font-semibold text-[#005f91] shrink-0">(v)</span>
                          <span>If a petition is presented for the administration or winding up of the data importer, whether in its personal or business capacity, which petition is not dismissed within the applicable period for such dismissal under applicable law; a winding up order is made; a receiver is appointed over any of its assets; a trustee in bankruptcy is appointed, if the data importer is an individual; a company voluntary arrangement is commenced by it; or any equivalent event in any jurisdiction occurs, then the data exporter, without prejudice to any other rights which it may have against the data importer, shall be entitled to terminate these clauses, in which case the authority shall be informed where required. In cases covered by (i), (ii), or (iv) above the data importer may also terminate these clauses.</span>
                        </li>
                      </ol>
                    </div>
                  </div>

                  {/* Paragraph b */}
                  <div className="flex items-start gap-2.5">
                    <span className="font-bold text-[#005f91] shrink-0">b.</span>
                    <span>Either party may terminate these clauses if (i) any Commission positive adequacy decision under Article 25(6) of Directive 95/46/EC (or any superseding text) is issued in relation to the country (or a sector thereof) to which the data is transferred and processed by the data importer, or (ii) Directive 95/46/EC (or any superseding text) becomes directly applicable in such country.</span>
                  </div>

                  {/* Paragraph c */}
                  <div className="flex items-start gap-2.5">
                    <span className="font-bold text-[#005f91] shrink-0">c.</span>
                    <span>The parties agree that the termination of these clauses at any time, in any circumstances and for whatever reason (except for termination under clause VI(c)) does not exempt them from the obligations and/or conditions under the clauses as regards the processing of the personal data transferred.</span>
                  </div>
                </div>
              </div>

              {/* Section 7: Description of the Transfer */}
              <div>
                <h5 className="text-[16px] font-semibold text-[#005f91] mb-2">7. Description of the Transfer</h5>
                <p className="text-slate-800 leading-relaxed pl-2">
                  The details of the transfer and of the personal data are specified in Privacy policy and terms and conditions.
                </p>
              </div>
            </div>

            {/* Grievance Officer */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Grievance Officer :</h3>
            <p className="mb-6 text-slate-800">
              In case of any complaints or grievances, the user may contact the Grievance Officer at:{" "}
              <a href="mailto:info@vidimeth.com" className="text-[#005f91] font-semibold underline hover:text-[#004a70]">
                info@vidimeth.com
              </a>
            </p>

            {/* Contact Us */}
            <h3 className="text-[20px] font-semibold text-[#0a1f44] mt-8 mb-3">Contact Us</h3>
            <p className="mb-8 text-slate-800">
              Please contact us for any questions, concerns or suggestions regarding our Privacy Policy.
            </p>

          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
